version: '2'
services:
  sonarqube:
    build: .
    ports:
     - 9000:9000
    environment:
     - SONARQUBE_JDBC_USERNAME=${DATABASE_USERNAME}
     - SONARQUBE_JDBC_PASSWORD=${DATABASE_PASSWORD}
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db/${DATABASE_NAME}
    links:
     - db
  db:
    image: "postgres:9.6.1-alpine"
    environment:
     - POSTGRES_USER=${DATABASE_USERNAME}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
